Feat/allow the evaluator send an txt or write the appointments in a text area (#229)
* add atribute validate note to model examinations board

* add display of the appoint text field

* adjusted display of appointment text

* add atribute validate note to model examinations board

* add display of the appoint text field

* adjusted display of appointment text

* fix indentation code

* add feature test for new fields

* fiz broke testsand add a new test for all evaluated for examination board model

* add test feature for appointment text area

* fix examination board note appoint text test

* fix error message in test

* Review PR #229 Issue #215

- Correct the identation
- Refactor the test name
- Add missing test

* Review PR #229 Issue #215

Upgrade should-matchers gem to solve the error:

  1) BaseActivity validates when info type is expected not to validate that :identifier cannot be empty/falsy
     Failure/Error: it { is_expected.not_to validate_presence_of(:identifier) }

     NoMethodError:
       undefined method `attribute_setter' for nil:NilClass
     # ./spec/models/base_activity_spec.rb:19:in `block (4 levels) in <main>'

Also necessary to correct some tests code to run in the new version of the gem

---------

Co-authored-by: AmandaCarolyneDeLima <amandaacarolyne@outlook.com>
Co-authored-by: Prof. Diego Marczal <37582258+MarczalTSIGP@users.noreply.github.com>
Co-authored-by: Diego Marczal <dmarczal@gmail.com>